- name: create ec2 and route53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-01c494b94c100e1d3
    sg_id: sg-043daf9713dbb52e3
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install aws python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - botocore
    - boto3

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print private IP addresses
    ansible.builtin.debug:
      msg: "{{ item.item }}: {{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"